services:
  namenode:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: namenode
    container_name: hadoop-namenode
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      ENSURE_NAMENODE_DIR: /tmp/hadoop-hadoop/dfs/name
    env_file:
      - ./hadoop.env
    command: ["hdfs", "namenode"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536
    networks:
      - bigdata-net

  datanode:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: datanode
    container_name: hadoop-datanode
    depends_on:
      namenode:
        condition: service_started
    ports:
      - "9864:9864"
      - "9866:9866"
    env_file:
      - ./hadoop.env
    command: ["hdfs", "datanode"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536
    networks:
      - bigdata-net

  resourcemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: resourcemanager
    container_name: hadoop-resourcemanager
    depends_on:
      datanode:
        condition: service_started
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
    command: ["yarn", "resourcemanager"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536
    networks:
      - bigdata-net

  nodemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: nodemanager
    container_name: hadoop-nodemanager
    depends_on:
      resourcemanager:
        condition: service_started
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env
    command: ["yarn", "nodemanager"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536
    networks:
      - bigdata-net

networks:
  bigdata-net:
    name: bigdata-network
    external: true
